### ISSUE TITLE
您好能否给我个联系方式，或者我联系您

### ISSUE THREAD

**Issue by axt178178** [yclown/MobileControlGuru#1]
您好我对这个项目感兴趣，请问可以给个联系方式或者您回复我我把我的联系方式给您，期待您的答复！

**Comment by yclown** [comment]
![a1708b72b803cd69bf68212ee2ba271](https://github.com/user-attachments/assets/7c83cfcc-8f64-4563-8d0c-d7981d2a261f)
你加我微信吧

**Comment by axt178178** [comment]
已经申请了，有时间的时候请同意一下

yclown ***@***.***> 于2024年9月29日周日 09:53写道：
