### ISSUE TITLE
大佬，建议加上手动息屏/亮屏功能

### ISSUE THREAD

**Issue by wind15030746** [yclown/MobileControlGuru#2]
长时间使用太费电了， 息屏情况下 又无法用指纹，而且部分涉及安全的界面也不支持投屏（黑屏），就无法操作了。

**Comment by yclown** [comment]
如果是安卓10以后的手机都支持无线调试，建议使用无限调试的方法，这样可以插着充电器使用。黑屏解锁的问题尝试在开发者选项里面启用OEM解锁功能

**Comment by wind15030746** [comment]
谢谢大佬回复，确实可以通过其他方式解决，但毕竟不方便， 不如一个按钮，或一个快捷键搞定方便。再次感谢大佬，您方便的话可以考虑增加下这个功能

**Comment by yclown** [comment]
息屏和亮屏原先就有的，在投屏的窗口，快捷点ctrl+O 息屏ctr+shift+O亮屏 你试试

**Comment by yclown** [comment]
投屏选项里有个手机息屏，就是投屏手机是息屏的，投屏窗口不受影响

**Comment by yclown** [comment]
[scrcpy快捷键](https://github.com/Genymobile/scrcpy/blob/master/doc/shortcuts.md) 投屏窗口的快捷键看这里

**Comment by wind15030746** [comment]
好的  感谢大佬
